import { Repository } from ".";

const defaultRepositoryFields = {
  "id": 118290693,
  "node_id": "MDEwOlJlcG9zaXRvcnkxMTgyOTA2OTM=",
  "name": "react-composer",
  "full_name": "jamesplease/react-composer",
  "private": false,
  "owner": {
    "login": "jamesplease",
    "id": 2322305,
    "node_id": "MDQ6VXNlcjIzMjIzMDU=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2322305?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jamesplease",
    "html_url": "https://github.com/jamesplease",
    "followers_url": "https://api.github.com/users/jamesplease/followers",
    "following_url": "https://api.github.com/users/jamesplease/following{/other_user}",
    "gists_url": "https://api.github.com/users/jamesplease/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jamesplease/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jamesplease/subscriptions",
    "organizations_url": "https://api.github.com/users/jamesplease/orgs",
    "repos_url": "https://api.github.com/users/jamesplease/repos",
    "events_url": "https://api.github.com/users/jamesplease/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jamesplease/received_events",
    "type": "User",
    "site_admin": false
  },
  "html_url": "https://github.com/jamesplease/react-composer",
  "description": "Compose render prop components",
  "fork": false,
  "url": "https://api.github.com/repos/jamesplease/react-composer",
  "forks_url": "https://api.github.com/repos/jamesplease/react-composer/forks",
  "keys_url": "https://api.github.com/repos/jamesplease/react-composer/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/jamesplease/react-composer/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/jamesplease/react-composer/teams",
  "hooks_url": "https://api.github.com/repos/jamesplease/react-composer/hooks",
  "issue_events_url": "https://api.github.com/repos/jamesplease/react-composer/issues/events{/number}",
  "events_url": "https://api.github.com/repos/jamesplease/react-composer/events",
  "assignees_url": "https://api.github.com/repos/jamesplease/react-composer/assignees{/user}",
  "branches_url": "https://api.github.com/repos/jamesplease/react-composer/branches{/branch}",
  "tags_url": "https://api.github.com/repos/jamesplease/react-composer/tags",
  "blobs_url": "https://api.github.com/repos/jamesplease/react-composer/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/jamesplease/react-composer/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/jamesplease/react-composer/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/jamesplease/react-composer/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/jamesplease/react-composer/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/jamesplease/react-composer/languages",
  "stargazers_url": "https://api.github.com/repos/jamesplease/react-composer/stargazers",
  "contributors_url": "https://api.github.com/repos/jamesplease/react-composer/contributors",
  "subscribers_url": "https://api.github.com/repos/jamesplease/react-composer/subscribers",
  "subscription_url": "https://api.github.com/repos/jamesplease/react-composer/subscription",
  "commits_url": "https://api.github.com/repos/jamesplease/react-composer/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/jamesplease/react-composer/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/jamesplease/react-composer/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/jamesplease/react-composer/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/jamesplease/react-composer/contents/{+path}",
  "compare_url": "https://api.github.com/repos/jamesplease/react-composer/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/jamesplease/react-composer/merges",
  "archive_url": "https://api.github.com/repos/jamesplease/react-composer/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/jamesplease/react-composer/downloads",
  "issues_url": "https://api.github.com/repos/jamesplease/react-composer/issues{/number}",
  "pulls_url": "https://api.github.com/repos/jamesplease/react-composer/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/jamesplease/react-composer/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/jamesplease/react-composer/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/jamesplease/react-composer/labels{/name}",
  "releases_url": "https://api.github.com/repos/jamesplease/react-composer/releases{/id}",
  "deployments_url": "https://api.github.com/repos/jamesplease/react-composer/deployments",
  "created_at": "2018-01-20T23:57:29Z",
  "updated_at": "2023-10-12T05:45:00Z",
  "pushed_at": "2022-04-28T19:21:52Z",
  "git_url": "git://github.com/jamesplease/react-composer.git",
  "ssh_url": "git@github.com:jamesplease/react-composer.git",
  "clone_url": "https://github.com/jamesplease/react-composer.git",
  "svn_url": "https://github.com/jamesplease/react-composer",
  "homepage": null,
  "size": 79,
  "stargazers_count": 612,
  "watchers_count": 612,
  "language": "JavaScript",
  "has_issues": true,
  "has_projects": false,
  "has_downloads": true,
  "has_wiki": false,
  "has_pages": false,
  "has_discussions": false,
  "forks_count": 17,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 3,
  "license": {
    "key": "mit",
    "name": "MIT License",
    "spdx_id": "MIT",
    "url": "https://api.github.com/licenses/mit",
    "node_id": "MDc6TGljZW5zZTEz"
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [
    "props",
    "react",
    "render"
  ],
  "visibility": "public",
  "forks": 17,
  "open_issues": 3,
  "watchers": 612,
  "default_branch": "master",
  "score": 1.0
} satisfies Repository

export function generateRepository(partialRepository: Partial<Repository>) {
  return {
    ...defaultRepositoryFields,
    ...partialRepository,
  } satisfies Repository
}
